# run once rake spec_prep
# run often (avoiding download) rake spec_standalone
fixtures:
  forge_modules:
      stdlib: "puppetlabs/stdlib"
      concat: "puppetlabs/concat"
      apt: "puppetlabs/apt"
  symlinks:
    x2go: "#{source_dir}"
