name         'ngiger-x2go'
version      '0.1.1'
summary      'x2go Puppet module.'
description  'Puppet module for x2go client and server.'
project_page 'https://github.com/ngiger/puppet-x2go'
license      'GNU General Public License v3 or Later (GPLv3+)'
author       'Niklaus Giger <niklaus.giger@member.fsf.org>'
dependency   'puppetlabs/apt', '>= 1.0'
